const DEFAULT_PRODUCTS = [
  // --- LAPTOPS ---
  {
    id: "rog-zephyrus-g16-2026",
    name: "ASUS ROG Zephyrus G16",
    price: 2499,
      variants: [
    { type: "size", values: ["S", "M", "L", "XL"] },
    { type: "color", values: ["Black", "White", "Red"] }
  ],

    category: "laptop",
    isHot: true,
    isNew: true,
    stock: 5,
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-slim gaming laptop with 3K OLED 240Hz display and CNC aluminum chassis.",
    brand: "ASUS",
    os: "Windows 11 Pro",
    cpu: "Intel Core Ultra 9 385H",
    deliveryEstimate: "3-5 days",
    specs: "RTX 5080, 32GB LPDDR5X, 2TB Gen5 SSD"
  },
  {
    id: "macbook-pro-m5",
    name: "MacBook Pro 14\" M5",
    price: 1999,
    category: "laptop",
    isHot: true,
    isNew: true,
    stock: 15,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    description: "The most powerful compact pro laptop with the all-new M5 chip.",
    brand: "Apple",
    os: "macOS Sequoia",
    cpu: "Apple M5 (12-core)",
    deliveryEstimate: "Tomorrow",
    specs: "14.2\" Liquid Retina XDR, 18GB Unified Memory"
  },
  {
    id: "xps-13-9345",
    name: "Dell XPS 13 Plus",
    price: 1399,
    category: "laptop",
    isHot: false,
    isNew: true,
    stock: 8,
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    description: "Borderless InfinityEdge display with touch function row.",
    brand: "Dell",
    os: "Windows 11 Home",
    cpu: "Intel Core Ultra 7 255U",
    deliveryEstimate: "2-4 days",
    specs: "Tandem OLED Display, 16GB RAM, 512GB SSD"
  },
  {
    id: "razer-blade-18-2026",
    name: "Razer Blade 18",
    price: 4299,
    category: "laptop",
    isHot: true,
    isNew: true,
    stock: 3,
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80",
    description: "Desktop replacement with 4K 200Hz display and Thunderbolt 5.",
    brand: "Razer",
    os: "Windows 11 Pro",
    cpu: "Intel Core Ultra 9 390HK",
    deliveryEstimate: "1 week",
    specs: "RTX 5090 (175W), 64GB RAM, 4TB SSD"
  },

  // --- PHONES ---
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro Max",
    price: 1199,
    category: "phone",
    isHot: true,
    isNew: true,
    stock: 20,
    image: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&fit=crop&w=800&q=80",
    description: "Titanium build with 48MP periscope telephoto lens.",
    brand: "Apple",
    os: "iOS 19",
    cpu: "A19 Pro Chip",
    deliveryEstimate: "Ships in 24h",
    specs: "6.7\" ProMotion, 256GB"
  },
  {
    id: "pixel-10-pro",
    name: "Google Pixel 10 Pro",
    price: 999,
    category: "phone",
    isHot: true,
    isNew: true,
    stock: 12,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80",
    description: "The ultimate AI phone with Tensor G5 and Gemini Ultra integration.",
    brand: "Google",
    os: "Android 16",
    cpu: "Tensor G5",
    deliveryEstimate: "3 days",
    specs: "Advanced Magic Eraser, 5000mAh"
  },
  {
    id: "z-fold-7",
    name: "Galaxy Z Fold 7",
    price: 1799,
    category: "phone",
    isHot: true,
    isNew: true,
    stock: 6,
    image: "https://images.unsplash.com/photo-1610945415295-d9baf060e871?auto=format&fit=crop&w=800&q=80",
    description: "Thinner, lighter, and stronger foldable with integrated S-Pen slot.",
    brand: "Samsung",
    os: "Android 15",
    cpu: "Snapdragon 8 Gen 5",
    deliveryEstimate: "5-7 days",
    specs: "7.6\" Dynamic AMOLED 2X, 12GB RAM"
  },

  // --- AUDIO ---
  {
    id: "sony-wh1000-xm6",
    name: "Sony WH-1000XM6",
    price: 399,
    category: "audio",
    isHot: true,
    isNew: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    description: "Next-gen noise cancellation with ultra-low latency lossless audio.",
    brand: "Sony",
    os: null,
    cpu: "Sony V3 Processor",
    deliveryEstimate: "Tomorrow",
    specs: "45h Battery, LDAC Support"
  },
  {
    id: "airpods-pro-3",
    name: "AirPods Pro (3rd Gen)",
    price: 249,
    category: "audio",
    isHot: true,
    isNew: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1588423770574-f199ba4a8b16?auto=format&fit=crop&w=800&q=80",
    description: "Enhanced spatial audio with heart rate tracking sensors.",
    brand: "Apple",
    os: null,
    cpu: "H3 Chip",
    deliveryEstimate: "Free shipping",
    specs: "USB-C, ANC 2.0"
  },

  // --- GAMING DESKTOPS ---
  {
    id: "alienware-r17",
    name: "Alienware Aurora R17",
    price: 3499,
    category: "desktop",
    isHot: true,
    isNew: true,
    stock: 4,
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    description: "Cryo-Tech liquid cooled gaming rig with RTX 5090.",
    brand: "Alienware",
    os: "Windows 11 Pro",
    cpu: "Intel Core Ultra 9 285K",
    deliveryEstimate: "10-12 days",
    specs: "NVIDIA RTX 5090, 64GB DDR5, 4TB SSD"
  },
  {
    id: "hp-omen-45l",
    name: "HP Omen 45L",
    price: 2199,
    category: "desktop",
    isHot: false,
    isNew: false,
    stock: 7,
    image: "https://images.unsplash.com/photo-1625842268584-8f3bf9ff16a1?auto=format&fit=crop&w=800&q=80",
    description: "Cryo Chamber cooling system for peak CPU performance.",
    brand: "HP",
    os: "Windows 11 Home",
    cpu: "AMD Ryzen 9 9950X",
    deliveryEstimate: "3-5 days",
    specs: "RTX 5070, 32GB RAM, 1TB SSD"
  },

  // --- WEARABLES ---
  {
    id: "apple-watch-u3",
    name: "Apple Watch Ultra 3",
    price: 799,
    category: "wearable",
    isHot: true,
    isNew: true,
    stock: 14,
    image: "https://images.unsplash.com/photo-1434493907317-a46b53b81846?auto=format&fit=crop&w=800&q=80",
    description: "Satin Black titanium finish with micro-LED display.",
    brand: "Apple",
    os: "watchOS 12",
    cpu: "S11 SiP",
    deliveryEstimate: "Ships tomorrow",
    specs: "72h Battery, GPS L5"
  },
  {
    id: "garmin-fenix-8",
    name: "Garmin Fenix 8 Solar",
    price: 899,
    category: "wearable",
    isHot: false,
    isNew: true,
    stock: 9,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    description: "Endurance multi-sport watch with unlimited solar battery life.",
    brand: "Garmin",
    os: "Garmin OS",
    cpu: "NXP i.MX",
    deliveryEstimate: "2-4 days",
    specs: "TOPO Maps, 10ATM Water Resistance"
  },

  // --- ACCESSORIES & POWER ---
  {
    id: "anker-737-v2",
    name: "Anker Prime 250W",
    price: 179,
    category: "power",
    isHot: true,
    isNew: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1619130772021-4b13009883ad?auto=format&fit=crop&w=800&q=80",
    description: "High-capacity power bank with smart digital display.",
    brand: "Anker",
    os: null,
    cpu: null,
    deliveryEstimate: "2 days",
    specs: "27650mAh, 250W Multi-port"
  },
  {
    id: "logitech-mx-master-4",
    name: "Logitech MX Master 4",
    price: 129,
    category: "accessory",
    isHot: true,
    isNew: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80",
    description: "The gold standard for productivity with MagSpeed scrolling.",
    brand: "Logitech",
    os: null,
    cpu: null,
    deliveryEstimate: "Tomorrow",
    specs: "8K DPI Optical, USB-C"
  },
  
  // --- TABLETS ---
  {
    id: "ipad-pro-m4-13",
    name: "iPad Pro 13\" (M4)",
    price: 1299,
    category: "tablet",
    isHot: true,
    isNew: false,
    stock: 11,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    description: "Incredibly thin design with Tandem OLED display.",
    brand: "Apple",
    os: "iPadOS 19",
    cpu: "Apple M4",
    deliveryEstimate: "Free delivery",
    specs: "Ultra Retina XDR, 256GB"
  },
  {
    id: "tab-s10-ultra",
    name: "Galaxy Tab S10 Ultra",
    price: 1199,
    category: "tablet",
    isHot: false,
    isNew: true,
    stock: 5,
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    description: "Massive 14.6\" screen for creators and multi-taskers.",
    brand: "Samsung",
    os: "Android 15",
    cpu: "Snapdragon 8 Gen 4",
    deliveryEstimate: "3-5 days",
    specs: "AMOLED 120Hz, IP68"
  },

  // --- SMART HOME (NEW CATEGORY) ---
  {
    id: "nest-cam-iq",
    name: "Google Nest Cam Ultra",
    price: 199,
    category: "smarthome",
    isHot: false,
    isNew: true,
    stock: 18,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80",
    description: "4K security camera with AI facial recognition.",
    brand: "Google",
    os: null,
    cpu: "Titan M2",
    deliveryEstimate: "Tomorrow",
    specs: "4K HDR, Night Vision"
  },
  {
    id: "philips-hue-starter",
    name: "Hue Bridge Gen 3",
    price: 159,
    category: "smarthome",
    isHot: false,
    isNew: false,
    stock: 22,
    image: "https://images.unsplash.com/photo-1550524514-9636edba3118?auto=format&fit=crop&w=800&q=80",
    description: "Smart lighting starter kit with 3 RGB bulbs.",
    brand: "Philips",
    os: null,
    cpu: null,
    deliveryEstimate: "2 days",
    specs: "Matter Compatible, 16M colors"
  },

  // --- MONITORS (NEW CATEGORY) ---
  {
    id: "odyssey-neo-g9",
    name: "Samsung Odyssey Neo G9",
    price: 1799,
    category: "monitor",
    isHot: true,
    isNew: false,
    stock: 4,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    description: "49\" curved gaming monitor with Quantum Mini-LED.",
    brand: "Samsung",
    os: null,
    cpu: null,
    deliveryEstimate: "1 week",
    specs: "240Hz, 1ms, Dual UHD"
  },
  {
    id: "lg-ultragear-32",
    name: "LG UltraGear OLED 32\"",
    price: 1299,
    category: "monitor",
    isHot: true,
    isNew: true,
    stock: 6,
    image: "https://images.unsplash.com/photo-1547115941-07904129b7f9?auto=format&fit=crop&w=800&q=80",
    description: "4K OLED gaming monitor with 480Hz dual-mode.",
    brand: "LG",
    os: null,
    cpu: null,
    deliveryEstimate: "4-6 days",
    specs: "0.03ms GtG, G-Sync"
  },

  // --- STORAGE ---
  {
    id: "samsung-t9-4tb",
    name: "Samsung T9 Portable SSD",
    price: 349,
    category: "storage",
    isHot: false,
    isNew: false,
    stock: 12,
    image: "https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?auto=format&fit=crop&w=800&q=80",
    description: "Rugged external SSD with 2000MB/s speeds.",
    brand: "Samsung",
    os: null,
    cpu: null,
    deliveryEstimate: "Tomorrow",
    specs: "4TB, USB 3.2 Gen 2x2"
  },

  // --- CONTINUING TO 50 ITEMS (SIMPLIFIED REPEATS WITH UNIQUE IDs) ---
  { id: "legion-pro-7i", name: "Lenovo Legion Pro 7i", price: 2899, category: "laptop", isHot: true, isNew: true, stock: 5, image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80", description: "Extreme gaming with Intel 14th Gen.", brand: "Lenovo", os: "Windows 11", cpu: "Core i9-14900HX", deliveryEstimate: "5 days", specs: "RTX 4090, 32GB RAM" },
  { id: "surface-pro-11", name: "Surface Pro 11", price: 1099, category: "tablet", isHot: false, isNew: true, stock: 9, image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80", description: "The most powerful 2-in-1 laptop.", brand: "Microsoft", os: "Windows 11 Home", cpu: "Snapdragon X Elite", deliveryEstimate: "3 days", specs: "13\" OLED, AI Copilot+" },
  { id: "nothing-phone-3", name: "Nothing Phone (3)", price: 649, category: "phone", isHot: true, isNew: true, stock: 15, image: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&fit=crop&w=800&q=80", description: "Glyph interface reinvented with AI.", brand: "Nothing", os: "Nothing OS 3.0", cpu: "Snapdragon 8 Gen 4", deliveryEstimate: "2 days", specs: "LTPO Display, 50MP Triple Cam" },
  { id: "bose-qc-ultra", name: "Bose QuietComfort Ultra", price: 429, category: "audio", isHot: false, isNew: false, stock: 20, image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80", description: "World-class noise cancellation.", brand: "Bose", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "Immersive Audio, 24h battery" },
  { id: "razer-deathadder-v4", name: "DeathAdder V4 Pro", price: 159, category: "accessory", isHot: true, isNew: true, stock: 25, image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80", description: "Ultra-lightweight competitive mouse.", brand: "Razer", os: null, cpu: null, deliveryEstimate: "Free shipping", specs: "30K Optical Sensor, 90h battery" },
  { id: "steam-deck-2", name: "Steam Deck 2", price: 649, category: "gaming", isHot: true, isNew: true, stock: 10, image: "https://images.unsplash.com/photo-1621336371460-640f19f8d28e?auto=format&fit=crop&w=800&q=80", description: "Next-gen PC gaming in your hands.", brand: "Valve", os: "SteamOS", cpu: "AMD Zen 5 Custom", deliveryEstimate: "2 weeks", specs: "OLED HDR, 1TB SSD" },
  { id: "playstation-6-slim", name: "PlayStation 6 Slim", price: 499, category: "gaming", isHot: true, isNew: true, stock: 2, image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80", description: "The future of console gaming.", brand: "Sony", os: "PS6 OS", cpu: "AMD RDNA 5", deliveryEstimate: "Ships May 1", specs: "8K Support, 2TB SSD" },
  { id: "ring-doorbell-pro-3", name: "Ring Video Doorbell Pro 3", price: 249, category: "smarthome", isHot: false, isNew: true, stock: 12, image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80", description: "Head-to-toe 2K video with Bird's Eye View.", brand: "Ring", os: null, cpu: null, deliveryEstimate: "3 days", specs: "3D Motion Detection" },
  { id: "nanoleaf-lines", name: "Nanoleaf Ultra-Lines", price: 299, category: "smarthome", isHot: true, isNew: false, stock: 5, image: "https://images.unsplash.com/photo-1550524514-9636edba3118?auto=format&fit=crop&w=800&q=80", description: "Backlit modular LED light bars.", brand: "Nanoleaf", os: null, cpu: null, deliveryEstimate: "5 days", specs: "Music Sync, Matter" },
  { id: "asus-rog-swift-500", name: "ROG Swift 540Hz", price: 899, category: "monitor", isHot: true, isNew: false, stock: 3, image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80", description: "World's fastest E-sports monitor.", brand: "ASUS", os: null, cpu: null, deliveryEstimate: "4 days", specs: "540Hz, TN Panel, G-Sync" },
  { id: "corsair-k100-v2", name: "Corsair K100 Air V2", price: 279, category: "accessory", isHot: false, isNew: true, stock: 15, image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=800&q=80", description: "Ultra-thin mechanical gaming keyboard.", brand: "Corsair", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "Cherry MX Ultra Low Profile" },
  { id: "wd-black-sn850x", name: "WD_BLACK 4TB SSD", price: 399, category: "storage", isHot: false, isNew: false, stock: 20, image: "https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?auto=format&fit=crop&w=800&q=80", description: "High-speed M.2 NVMe gaming storage.", brand: "Western Digital", os: null, cpu: null, deliveryEstimate: "2 days", specs: "7300MB/s, Heatsink included" },
  { id: "kindle-paperwhite-2026", name: "Kindle Paperwhite 13", price: 189, category: "tablet", isHot: false, isNew: true, stock: 30, image: "https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80", description: "Color e-ink display for the first time.", brand: "Amazon", os: "Kindle OS", cpu: null, deliveryEstimate: "Tomorrow", specs: "7\" Color E-Ink, Waterproof" },
  { id: "gopro-hero-14", name: "GoPro HERO14 Black", price: 449, category: "camera", isHot: true, isNew: true, stock: 12, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80", description: "6K/60fps video with HyperSmooth 7.0.", brand: "GoPro", os: null, cpu: "GP3 Chip", deliveryEstimate: "3 days", specs: "Edge-to-edge screen" },
  { id: "dji-mini-5-pro", name: "DJI Mini 5 Pro", price: 759, category: "camera", isHot: true, isNew: true, stock: 8, image: "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&w=800&q=80", description: "Under 249g drone with 4K/120fps vertical video.", brand: "DJI", os: null, cpu: null, deliveryEstimate: "5 days", specs: "Omnidirectional Sensing" },
  { id: "anker-maggo-v3", name: "Anker MagGo 3-in-1", price: 109, category: "power", isHot: false, isNew: true, stock: 25, image: "https://images.unsplash.com/photo-1619130772021-4b13009883ad?auto=format&fit=crop&w=800&q=80", description: "Qi2 certified folding charging station.", brand: "Anker", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "15W MagSafe, compact" },
  { id: "steelseries-nova-pro", name: "Arctis Nova Pro Wireless", price: 349, category: "audio", isHot: true, isNew: false, stock: 10, image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80", description: "Hot-swappable battery gaming headset.", brand: "SteelSeries", os: null, cpu: null, deliveryEstimate: "2 days", specs: "ANC, Hi-Res Audio" },
  { id: "wyze-cam-v4", name: "Wyze Cam v4 Pro", price: 59, category: "smarthome", isHot: true, isNew: true, stock: 50, image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80", description: "Affordable 2K security with spotlight.", brand: "Wyze", os: null, cpu: null, deliveryEstimate: "4 days", specs: "IP65, AI Person Detection" },
  { id: "elgato-stream-deck-mk3", name: "Stream Deck MK.3", price: 149, category: "accessory", isHot: false, isNew: true, stock: 18, image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80", description: "The creator's essential with rotary dials.", brand: "Elgato", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "15 LCD Keys, 4 Dials" },
  { id: "oneplus-14-pro", name: "OnePlus 14 Pro", price: 899, category: "phone", isHot: false, isNew: true, stock: 14, image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80", description: "150W fast charging flagship.", brand: "OnePlus", os: "OxygenOS 16", cpu: "Snapdragon 8 Gen 5", deliveryEstimate: "3 days", specs: "Hasselblad Camera, 16GB RAM" },
  { id: "philips-hue-play-sync", name: "Hue Play Sync Box 8K", price: 269, category: "smarthome", isHot: false, isNew: true, stock: 6, image: "https://images.unsplash.com/photo-1550524514-9636edba3118?auto=format&fit=crop&w=800&q=80", description: "Sync lights with 8K/60Hz HDMI content.", brand: "Philips", os: null, cpu: null, deliveryEstimate: "1 week", specs: "HDMI 2.1, 4 ports" },
  { id: "shure-sm7db", name: "Shure SM7dB", price: 499, category: "audio", isHot: true, isNew: false, stock: 8, image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80", description: "Podcast microphone with built-in preamp.", brand: "Shure", os: null, cpu: null, deliveryEstimate: "3 days", specs: "XLR, Cardioid" },
  { id: "alienware-aw3423dwf", name: "Alienware 34 Curved OLED", price: 999, category: "monitor", isHot: true, isNew: false, stock: 4, image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80", description: "QD-OLED ultrawide gaming monitor.", brand: "Alienware", os: null, cpu: null, deliveryEstimate: "1 week", specs: "165Hz, 0.1ms, HDR True Black" },
  { id: "tp-link-deco-be85", name: "Deco BE85 Wi-Fi 7", price: 999, category: "smarthome", isHot: true, isNew: true, stock: 10, image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80", description: "Tri-band Wi-Fi 7 mesh system.", brand: "TP-Link", os: null, cpu: null, deliveryEstimate: "2 days", specs: "22Gbps, Multi-Gig Ports" },
  { id: "eero-max-7", name: "eero Max 7 Router", price: 599, category: "smarthome", isHot: false, isNew: true, stock: 15, image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80", description: "Fastest Amazon mesh router ever.", brand: "Amazon", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "10Gbps Ethernet, Wi-Fi 7" },
  { id: "blue-yeti-gx", name: "Blue Yeti GX", price: 149, category: "audio", isHot: false, isNew: true, stock: 20, image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80", description: "Dynamic RGB gaming microphone.", brand: "Logitech G", os: null, cpu: null, deliveryEstimate: "2 days", specs: "USB-C, LIGHTSYNC" },
  { id: "samsung-viewfinity-s9", name: "Samsung ViewFinity S9", price: 1599, category: "monitor", isHot: false, isNew: false, stock: 5, image: "https://images.unsplash.com/photo-1547115941-07904129b7f9?auto=format&fit=crop&w=800&q=80", description: "5K display for creative professionals.", brand: "Samsung", os: null, cpu: null, deliveryEstimate: "3 days", specs: "5K, Matte Display, Thunderbolt 4" },
  { id: "mac-studio-m4-ultra", name: "Mac Studio M4 Ultra", price: 3999, category: "desktop", isHot: true, isNew: true, stock: 3, image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80", description: "The ultimate desktop powerhouse.", brand: "Apple", os: "macOS Sequoia", cpu: "M4 Ultra (24-core)", deliveryEstimate: "2 weeks", specs: "128GB Unified Memory, 2TB" },
  { id: "insta360-x5", name: "Insta360 X5", price: 549, category: "camera", isHot: true, isNew: true, stock: 10, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80", description: "8K 360-degree action camera.", brand: "Insta360", os: null, cpu: null, deliveryEstimate: "3 days", specs: "FlowState Stabilization" },
  { id: "razer-iskur-v2", name: "Razer Iskur V2", price: 649, category: "gaming", isHot: false, isNew: true, stock: 5, image: "https://images.unsplash.com/photo-1598550476439-6847785fce6c?auto=format&fit=crop&w=800&q=80", description: "Ergonomic gaming chair with adaptive lumbar.", brand: "Razer", os: null, cpu: null, deliveryEstimate: "1 week", specs: "EPU Synthetic Leather" },
  { id: "secretlab-titan-evo", name: "Secretlab TITAN Evo 2026", price: 599, category: "gaming", isHot: true, isNew: true, stock: 8, image: "https://images.unsplash.com/photo-1598550476439-6847785fce6c?auto=format&fit=crop&w=800&q=80", description: "Award-winning comfort for long sessions.", brand: "Secretlab", os: null, cpu: null, deliveryEstimate: "4 days", specs: "Magnetic Head Pillow" },
  { id: "belkin-boostcharge-pro", name: "Belkin 140W Gan Charger", price: 89, category: "power", isHot: false, isNew: false, stock: 40, image: "https://images.unsplash.com/photo-1619130772021-4b13009883ad?auto=format&fit=crop&w=800&q=80", description: "4-Port GaN Wall Charger.", brand: "Belkin", os: null, cpu: null, deliveryEstimate: "Tomorrow", specs: "USB-C PD 3.1" },
  { id: "nanoleaf-shapes", name: "Nanoleaf Shapes Hexagons", price: 199, category: "smarthome", isHot: false, isNew: false, stock: 20, image: "https://images.unsplash.com/photo-1550524514-9636edba3118?auto=format&fit=crop&w=800&q=80", description: "Modular touch-reactive light panels.", brand: "Nanoleaf", os: null, cpu: null, deliveryEstimate: "3 days", specs: "Rhythm Sync, 16M Colors" }
];

